version: '3.1'

services:
  front_modrp:
    build:
      context: ../modrp-basic-dash/
    links:
      - back_modrp
    depends_on:
      - db_modrp
      - back_modrp
    ports:
      - 8012:3000
    restart: always

  back_modrp:
    build:
      context: ../modrp-basic-api/
    links:
      - db_modrp
    depends_on:
      - db_modrp
    ports:
      - 5312:5312
    restart: always

  db_modrp:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: modrp
      POSTGRES_DB: modrp
    ports:
      - 5412:5432
    volumes:
      - db_modrp:/var/lib/postgresql/data
    restart: always

volumes:
  db_modrp:
